### ISSUE TITLE
Changes in  DarkComet?

### ISSUE THREAD

**Issue by timleedy** [kevthehermit/RATDecoders#27]
I came across a sample on VT (19913fd36da6d714d895e7018fcb32213b48859e) which the decoder doesn't handle.  The decoder gets the key (#KCMDDC51#-890), but the entry.name list doesn't match the naming in BASE_CONFIG (A1,A2,B1,B2,C1,C2,D1,D2,DVCLAL,E1,PACKAGEINFO).  I did some debugging and an error is thrown ('odd length string') when calling unhexify(data).  Ping me offline if you need the file.

**Comment by sysopfb** [comment]
DarkComet is in the clear embedded in resources, I added a pull request that does a naive implementation of checking for this. Probably be better to check for a failure to find the config and then do a passover on any embedded files you can find in the PE?

**Comment by kevthehermit** [comment]
Looks good thanks for the pull.
