### ISSUE TITLE
[BUG] This statement is always true!

### ISSUE THREAD

**Issue by catsuryuu** [kevthehermit/RATDecoders#42]
https://github.com/kevthehermit/RATDecoders/blob/39c28645c35c03aa3f12ccd60158b98668d004a3/StandAlone/NanoCore.py#L180

Probably should be `if str(entry.name) == "RC_DATA" or str(entry.name) == "RCData":`

**Comment by snemes** [comment]
Yeah, nice find. Indeed, this is not how the "or" operator works in Python (or in any programming language to be honest), this is interpreted as `(str(entry.name) == "RC_DATA") or ("RCData")` (due to the operator precedence rules). :smile: 

I have submitted a merge request to fix this.

**Comment by kevthehermit** [comment]
Thanks, I actually found some time this week to work on converting this to a library with python3 compatibility. Have fixed this in that branch. - https://github.com/kevthehermit/RATDecoders/tree/library
